### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by Skruf90** [mrsmn/wookie#10]
Do you have a install guide?

**Comment by mrsmn** [comment]
Hi there,

there is no installation, simply execute the wookie.py file in the wookie directory with the following:

```
./wookie.py <start> or <screen>
<start> to run wookie in standard mode
<screen> to run wookie in a detached screen session
```

Cheers.

**Comment by Skruf90** [comment]
sudo: ./wookie.py: command not found

**Comment by Skruf90** [comment]
Are you on gitter? Really want this script to work.

**Comment by mrsmn** [comment]
Here are more details if you need them:

```
git clone https://github.com/mrsmn/wookie.git
cd wookie/wookie
```

Edit the config.py file to suit your needs, then:

```
python wookie.py <start> or <screen>
```

And sorry no, I'm not on gitter (don't even have a clue what it's supposed to be :stuck_out_tongue: )

Cheers.

**Comment by Skruf90** [comment]
Traceback (most recent call last):
  File "wookie.py", line 9, in <module>
    import irclib
ImportError: No module named irclib

2015-10-09 21:44 GMT+02:00 Martin Simon <notifications@github.com>:

**Comment by Skruf90** [comment]
Getting the following error: 

Traceback (most recent call last):
  File "wookie.py", line 9, in <module>
    import irclib
ImportError: No module named irclib

**Comment by mrsmn** [comment]
You'll need to install the irclib module: https://pypi.python.org/pypi/python-irclib/

**Comment by Skruf90** [comment]
Traceback (most recent call last):
  File "wookie.py", line 21, in <module>
    from django.utils.encoding import smart_str
ImportError: No module named django.utils.encoding

**Comment by mrsmn** [comment]
Fixed by doing:

```
pip install django
```

**Comment by Skruf90** [comment]
Fixed now. Bot is running :). Can the bot fetch rss from .xml aswell?

2015-10-09 22:14 GMT+02:00 Martin Simon <notifications@github.com>:

**Comment by mrsmn** [comment]
Nope, it can't but if you have played with python a bit, it should be pretty easy to implement.

Cheers.

**Comment by grm34** [comment]
The bot fetch xml since v.3.0 :)
