### ISSUE TITLE
Bot will not start.

### ISSUE THREAD

**Issue by Scenepirat** [mrsmn/wookie#11]
Hi, I'm trying to get up and running for hours a bot. But somehow want the not start.

What I've done everything. All necessary packages I installed.

Python 2.7

apt-get install python-pip
pip install feedparser
pip install django 
wget http://downloads.sourceforge.net/project/python-irclib/python-irclib-0.6.4.zip
unzip python-irclib-0.6.4.zip
cd python-irclib-0.6.4
python setup.py 
python setup.py install
python
>> import irclib

But if i try to start the Bot i get errors. 
------------------------------------------------------------------------------------

root@68a335f4cb:/home/wookie/wookie# python wookie.py start
Traceback (most recent call last):
  File "wookie.py", line 365, in <module>
    main()
  File "wookie.py", line 355, in main
    bot.start()
  File "/usr/local/lib/python2.7/dist-packages/irclib.py", line 1182, in start
    self.ircobj.process_forever()
  File "/usr/local/lib/python2.7/dist-packages/irclib.py", line 239, in process_forever
    self.process_once(timeout)
  File "/usr/local/lib/python2.7/dist-packages/irclib.py", line 224, in process_once
    self.process_data(i)
  File "/usr/local/lib/python2.7/dist-packages/irclib.py", line 192, in process_data
    c.process_data()
  File "/usr/local/lib/python2.7/dist-packages/irclib.py", line 662, in process_data
    self._handle_event(Event(command, prefix, target, arguments))
  File "/usr/local/lib/python2.7/dist-packages/irclib.py", line 666, in _handle_event
    self.irclibobj._handle_event(self, event)
  File "/usr/local/lib/python2.7/dist-packages/irclib.py", line 346, in _handle_event
    if handler[1](connection, event) == "NO MORE":
  File "/usr/local/lib/python2.7/dist-packages/irclib.py", line 1117, in _dispatcher
    getattr(self, m)(c, e)
  File "wookie.py", line 73, in on_welcome
    self.announce_refresh()
  File "wookie.py", line 271, in announce_refresh
    entry.title).split(' - ', 1)[1].replace(' ', '.')
IndexError: list index out of range

Do you have an Idea? 

greets

**Comment by grm34** [comment]
Hi, you must use python-irclib-0.4.8:

`wget http://sourceforge.net/projects/python-irclib/files/python-irclib/0.4.8/python-irclib-0.4.8.tar.gz
tar -zxvf python-irclib-0.4.8.tar.gz && rm python-irclib-0.4.8.tar.gz && cd python-irclib-0.4.8
python install.py`

But it seems to be a problem with the feed rss/xml you are trying to use. The bot fails getting items titles of your feed.
Can you paste your config file or give the feed you try to use with?

**Comment by mrsmn** [comment]
Hi there,

@grm34 is right, your feed isn't working with wookie's code. As a side note, wookie was developed to match a pretty specific RSS feed so anyone trying to use it will have to adapt the code quite a bit.

Hope this helps.

Cheers.

**Comment by Scenepirat** [comment]
Oh i think xml feeds are not implemented so it doesnt work. i try an other RSS Feed and it seems to be work. I know myself with Python unfortunately not really good. But there will be by your side again an XML Enhancements? One question I have. Can I read multiple feeds? Or just one.

Thanks a lot for your quick help.

**Comment by grm34** [comment]
You're right, and  as @mrsmn said, it match a specific feed. I can adapt it for you with the feeds you wanna use.
And yes, you can use multiple feeds, "announce setting" is a list so you can put feeds like that : [http://feed1.com/rss, http://feed2.com/rss, http://feed2.com/rss]

**Comment by Scenepirat** [comment]
i have send you an mail @grm34 

Thank @mrsmn and @grm34 for your help!
