### ISSUE TITLE
Readme install instructions has an error

### ISSUE THREAD

**Issue by amici-ursi** [mrsmn/wookie#12]
Line 28 of the readme, in the **required** section, should be

    python setup.py install

**Comment by mrsmn** [comment]
Hi there,

thanks for noticing the error but actually it should neither.
```wookie```doesn't come with a setup script and is simply run with ```python wookie.py start/screen```
I'll fix it ASAP.
Cheers.

**Comment by mrsmn** [comment]
Fixed in commit:2b26ddab3db860c90d6b0d3ba72aca05ee07a3e0. Thanks again for reporting.

Cheers.
