### ISSUE TITLE
search function

### ISSUE THREAD

**Issue by Argon-D** [mrsmn/wookie#16]
Hi, first of all , thank you for this amazin bot. I get it work with RSS feed. I have 2 issues and I hope you can help me to fix :>  

1) There is a way to edit the spam on IRC ( change color for example)
2) I am using it for predb.ovh and i would like to know if there is a possibility to search rls in IRC ( for example type !search or !find )
I am asking it because in bot description there is : API Search 
Actually predb.ovh use this API  https://predb.ovh/api/v1/  but i can't get it works :( , i add that link into the config with no result

Thanks again !

**Comment by barnumbirr** [comment]
Hey there,

thank you for the kind words, glad you like the project. I'll try to answer your questions in as much details as I can:

>     1. There is a way to edit the spam on IRC ( change color for example)

Not sure why you mean by "spam". [Colors are defined in the class init](https://github.com/barnumbirr/wookie/blob/master/wookie/wookie.py#L56) then called [when the bot outputs data](https://github.com/barnumbirr/wookie/blob/master/wookie/wookie.py#L347). Should be rather easy to change colors to your hearts contempt.

>     2. I am using it for predb.ovh and i would like to know if there is a possibility to search rls in IRC ( for example type !search or !find )
>        I am asking it because in bot description there is : API Search
>        Actually predb.ovh use this API  https://predb.ovh/api/v1/  but i can't get it works :( , i add that link into the config with no result

The search capability of the bot is implemented [in this function](https://github.com/barnumbirr/wookie/blob/master/wookie/wookie.py#L171). As the bot wasn't  originally designed to work with `predb.ovh`, you'll have to adapt the URL constructor as well as the formatting of the output data.

Hope this helps.

Cheers.

**Comment by Argon-D** [comment]
Hi, first of all thanks for the quick reply :) . I've done with successfully the editing about colors and the outputs data. Unluckily i don't understand the line of codes about search. What was the original search command? i mean was .s or !s because I dont know how add it in the code :(

**Comment by barnumbirr** [comment]
[The search command is already defined in the code](https://github.com/barnumbirr/wookie/blob/master/wookie/wookie.py#L267), no need to add it.
I'll close this issue for now, don't hesitate to open another one if you have more questions.
Cheers.
