### ISSUE TITLE
Blowfish

### ISSUE THREAD

**Issue by zer0c0nf** [mrsmn/wookie#9]
Bonjour et merci pour ton super bot :)

Est-il possible que tu ajoutes le support du blowfish en CBC?

Merci à toi!

**Comment by c0ding** [comment]
Plop,

je vois pas vraiment l'intérêt de rajouter une encryption de style Blowfish a ce genre de bot. Aurais-tu des arguments particuliers qui pourraient me pousser à rajouter ce feature?

Merci.

**Comment by mrsmn** [comment]
No feedback in six months.
Closed.
